language: node.js
node_js:
  - "node"

sudo: required

services:
  - docker

install:
  - npm install

script:
  - npm run build

after_success:
  - docker login -u "mhk0116" -p "0dec0f06-5ae9-4a1e-af34-59f1d5a304c9"
  - docker build -t mhk0116/eureka_front .
  - docker push mhk0116/eureka_front
